# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
# O instrutor usa uma imagem prórpia ao invés de usar a oficial do mysql porque ele teve problemas com a oficial :-S
version: '3.4'

services:
  db:
    image: rest-with-aspnet-udemy-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: db/Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: masterdba-docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: masterdba-docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports: 
      - 3308:3306
    networks: 
      - udemy-network
      
  rest-with-aspnet-udemy:
    image: rest-with-aspnet-udemy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on: 
      - db
    networks: 
      - udemy-network
    
networks: 
  udemy-network:
    driver: bridge